In [117]:
import tensorflow as tf

In [118]:
import pandas as pd
df= pd.read_csv("../data/amazon_reviews.csv")
df.head()

reviewId                userName  \
0  429cfc01-1873-4cf6-b81e-f31202204776             Love Kitten   
1  845c5c60-30b1-4b77-9dc6-5c5836cf4cc8  David Lane (littleBIG)   
2  7873e006-d433-4cc8-b414-07f3a0f09720           Emery Hayward   
3  84daaec8-a441-424d-95ea-30d0a57ed6d1        Sohaila Elzayady   
4  97613d78-c374-4b8a-a439-a45067335597                   mo jo   

                                             content  score  thumbsUpCount  \
0    Too expensive I once spend 200.00 on 30 markers      1              0   
1                               it's very functional      5              0   
2           Trash app login function now long works.      1              0   
3                          One of my favorite apps 🥰      5              0   
4  Lost my former purchases and my wish list this...      3              1   

  reviewCreatedVersion                   at  appVersion  
0                  NaN  2024-05-12 23:25:39         NaN  
1           28.9.2.100  2024-05-12 23:15:57  28.9.2.100  
2           28.9.2.100  2024-05-12 23:10:51  28.9.2.100  
3           28.9.2.100  2024-05-12 23:00:33  28.9.2.100  
4           28.9.2.100  2024-05-12 22:56:42  28.9.2.100

In [119]:
df[:2000]

reviewId                userName  \
0     429cfc01-1873-4cf6-b81e-f31202204776             Love Kitten   
1     845c5c60-30b1-4b77-9dc6-5c5836cf4cc8  David Lane (littleBIG)   
2     7873e006-d433-4cc8-b414-07f3a0f09720           Emery Hayward   
3     84daaec8-a441-424d-95ea-30d0a57ed6d1        Sohaila Elzayady   
4     97613d78-c374-4b8a-a439-a45067335597                   mo jo   
...                                    ...                     ...   
1995  fb3d887a-9d21-43fd-acde-ed4159847c53           Tenecia Sanft   
1996  366698bc-d508-477f-8bc6-284293ffa976                Birdsong   
1997  ac581311-1ddb-41c7-9ed6-7ee040f8b3ce                 Geo Kay   
1998  2e3e81df-a4a5-40e5-9857-1b3116fff55f         joan villalobos   
1999  75e3bf9b-d141-4f81-9a77-30cdee615809             danny sweet   

                                                content  score  thumbsUpCount  \
0       Too expensive I once spend 200.00 on 30 markers      1              0   
1                                  it's very functional      5              0   
2              Trash app login function now long works.      1              0   
3                             One of my favorite apps 🥰      5              0   
4     Lost my former purchases and my wish list this...      3              1   
...                                                 ...    ...            ...   
1995  Search is atrocious. It's downright disrespect...      1              1   
1996  This app is starting to freeze and crash on my...      2              1   
1997  What is wrong with the app? It says I can't ch...      2              0   
1998  This is like the 6th time Amazon prime takes m...      1              0   
1999  App has been acting weird won't show current o...      1              0   

     reviewCreatedVersion                   at  appVersion  
0                     NaN  2024-05-12 23:25:39         NaN  
1              28.9.2.100  2024-05-12 23:15:57  28.9.2.100  
2              28.9.2.100  2024-05-12 23:10:51  28.9.2.100  
3              28.9.2.100  2024-05-12 23:00:33  28.9.2.100  
4              28.9.2.100  2024-05-12 22:56:42  28.9.2.100  
...                   ...                  ...         ...  
1995           28.4.0.100  2024-03-02 12:10:08  28.4.0.100  
1996           28.4.0.100  2024-03-04 14:43:27  28.4.0.100  
1997           28.4.0.100  2024-02-21 18:58:20  28.4.0.100  
1998           28.4.0.100  2024-03-04 01:17:33  28.4.0.100  
1999           28.4.0.100  2024-03-02 18:30:11  28.4.0.100  

[2000 rows x 8 columns]

In [120]:
text="/n".join(df[:2000]["content"].tolist())
# final_data=[]
# for i in text.split("/n"):
#     final_data.append(i.split())
# final_data


In [121]:
tokenizer=tf.keras.preprocessing.text.Tokenizer()

In [123]:
tokenizer.fit_on_texts([text])
tokenizer.word_index

{'the': 1,
 'to': 2,
 'i': 3,
 'and': 4,
 'it': 5,
 'a': 6,
 'is': 7,
 'for': 8,
 'my': 9,
 'app': 10,
 'of': 11,
 'amazon': 12,
 'on': 13,
 'you': 14,
 'in': 15,
 'have': 16,
 'that': 17,
 'they': 18,
 'not': 19,
 'this': 20,
 'with': 21,
 'but': 22,
 'me': 23,
 'be': 24,
 'or': 25,
 'are': 26,
 "it's": 27,
 'so': 28,
 'when': 29,
 'now': 30,
 'get': 31,
 'just': 32,
 'all': 33,
 'was': 34,
 'no': 35,
 'an': 36,
 'prime': 37,
 'if': 38,
 'items': 39,
 'from': 40,
 'as': 41,
 'up': 42,
 'at': 43,
 'time': 44,
 'has': 45,
 'order': 46,
 'your': 47,
 "don't": 48,
 'even': 49,
 'delivery': 50,
 'been': 51,
 'can': 52,
 'service': 53,
 "can't": 54,
 'what': 55,
 'do': 56,
 'like': 57,
 "i'm": 58,
 'customer': 59,
 'had': 60,
 'ni': 61,
 'out': 62,
 'will': 63,
 'because': 64,
 'more': 65,
 'item': 66,
 'shopping': 67,
 'there': 68,
 'search': 69,
 'day': 70,
 'use': 71,
 'shipping': 72,
 'one': 73,
 'account': 74,
 'want': 75,
 'their': 76,
 'them': 77,
 'very': 78,
 'back': 79,
 "i've": 8

In [125]:
input_sequence=[]
step=0
for sen in text.split("/n"):
    token_sen=tokenizer.texts_to_sequences([sen])[0]
    for i in range(1,len(token_sen)):
        input_sequence.append(token_sen[:i+1])
    print(step)
    step+=1
len(input_sequence)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

107151

In [126]:
input_sequence

[[168, 584],
 [168, 584, 3],
 [168, 584, 3, 308],
 [168, 584, 3, 308, 598],
 [168, 584, 3, 308, 598, 1833],
 [168, 584, 3, 308, 598, 1833, 1225],
 [168, 584, 3, 308, 598, 1833, 1225, 13],
 [168, 584, 3, 308, 598, 1833, 1225, 13, 503],
 [168, 584, 3, 308, 598, 1833, 1225, 13, 503, 3528],
 [27, 78],
 [27, 78, 1457],
 [539, 10],
 [539, 10, 1005],
 [539, 10, 1005, 866],
 [539, 10, 1005, 866, 30],
 [539, 10, 1005, 866, 30, 259],
 [539, 10, 1005, 866, 30, 259, 254],
 [73, 11],
 [73, 11, 9],
 [73, 11, 9, 1334],
 [73, 11, 9, 1334, 227],
 [73, 11, 9, 1334, 227, 2615],
 [419, 9],
 [419, 9, 3530],
 [419, 9, 3530, 447],
 [419, 9, 3530, 447, 4],
 [419, 9, 3530, 447, 4, 9],
 [419, 9, 3530, 447, 4, 9, 504],
 [419, 9, 3530, 447, 4, 9, 504, 255],
 [419, 9, 3530, 447, 4, 9, 504, 255, 20],
 [419, 9, 3530, 447, 4, 9, 504, 255, 20, 34],
 [419, 9, 3530, 447, 4, 9, 504, 255, 20, 34, 78],
 [419, 9, 3530, 447, 4, 9, 504, 255, 20, 34, 78, 867],
 [419, 9, 3530, 447, 4, 9, 504, 255, 20, 34, 78, 867, 18],
 [419, 9

In [127]:
input_sequence[]

SyntaxError: invalid syntax (837115628.py, line 1)

In [128]:
max_sen_lenth=max(map(lambda x : len(x),input_sequence))

In [129]:
max_sen_lenth

108

In [130]:
padded_input_sequence=tf.keras.preprocessing.sequence.pad_sequences(
    input_sequence,
    maxlen=max_sen_lenth,
    padding="pre"
)

In [131]:
len(padded_input_sequence)

107151

In [132]:
padded_input_sequence.shape

(107151, 108)

In [133]:
padded_input_sequence

array([[   0,    0,    0, ...,    0,  168,  584],
       [   0,    0,    0, ...,  168,  584,    3],
       [   0,    0,    0, ...,  584,    3,  308],
       ...,
       [   0,    0,    0, ...,   45, 1899,  124],
       [   0,    0,    0, ..., 1899,  124,  289],
       [   0,    0,    0, ...,  124,  289,  115]])

In [134]:
X=padded_input_sequence[:,:-1]
X

array([[   0,    0,    0, ...,    0,    0,  168],
       [   0,    0,    0, ...,    0,  168,  584],
       [   0,    0,    0, ...,  168,  584,    3],
       ...,
       [   0,    0,    0, ...,  693,   45, 1899],
       [   0,    0,    0, ...,   45, 1899,  124],
       [   0,    0,    0, ..., 1899,  124,  289]])

In [135]:
y=padded_input_sequence[:,-1]
y

array([584,   3, 308, ..., 124, 289, 115])

In [136]:
num_of_token=len(tokenizer.word_counts)

In [138]:
num_of_token

6644

In [137]:
y=tf.keras.utils.to_categorical(y,num_classes=num_of_token+1)

In [139]:
model=tf.keras.Sequential([
    tf.keras.layers.Embedding(num_of_token+1,200),
     tf.keras.layers.LSTM(150),
     tf.keras.layers.Dense(num_of_token+1,activation="softmax")
    ])

In [140]:
model.compile(
    loss="categorical_crossentropy",
    optimizer="adam",
    metrics=["accuracy"]
)

In [141]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [144]:
model.fit(X,y,epochs=5)

Epoch 1/5
3349/3349 ━━━━━━━━━━━━━━━━━━━━ 266s 79ms/step - accuracy: 0.5438 - loss: 2.0414
Epoch 2/5
3349/3349 ━━━━━━━━━━━━━━━━━━━━ 257s 77ms/step - accuracy: 0.5746 - loss: 1.9011
Epoch 3/5
3349/3349 ━━━━━━━━━━━━━━━━━━━━ 250s 75ms/step - accuracy: 0.5990 - loss: 1.7844
Epoch 4/5
3349/3349 ━━━━━━━━━━━━━━━━━━━━ 251s 75ms/step - accuracy: 0.6187 - loss: 1.6905
Epoch 5/5
3349/3349 ━━━━━━━━━━━━━━━━━━━━ 253s 76ms/step - accuracy: 0.6359 - loss: 1.6045


In [113]:
text_text='Too expensive I '
test_vec=tokenizer.texts_to_sequences([text_text])[0]
pad_test_vec = tf.keras.preprocessing.sequence.pad_sequences( [test_vec],
    maxlen=max_sen_lenth,
    padding="pre")

In [114]:
test_vec

[129, 291, 4]

In [115]:
import numpy as np

pred_index=np.argmax(model.predict([pad_test_vec])[0])
pred_index

tokenizer.index_word.get(pred_index)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step


'once'

In [116]:
text=input()
for i in range(5):
    test_vec=tokenizer.texts_to_sequences([text_text])[0]
    pad_test_vec = tf.keras.preprocessing.sequence.pad_sequences( [test_vec],
            maxlen=max_sen_lenth,
        padding="pre")
    pred_vec=np.argmax(model.predict([pad_test_vec])[0])
    pred_text=tokenizer.index_word.get(pred_index)
    text+=" "+pred_text
    print(text)

 I


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
I once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
I once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
I once once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
I once once once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
I once once once once once


In [107]:
text=input()
for i in range(5):
    test_vec=tokenizer.texts_to_sequences([text_text])[0]
    pad_test_vec = tf.keras.preprocessing.sequence.pad_sequences( [test_vec],
            maxlen=max_sen_lenth,
        padding="pre")
    pred_vec=np.argmax(model.predict([pad_test_vec])[0])
    pred_text=tokenizer.index_word.get(pred_index)
    text+=" "+pred_text
    print(text)

 One of my


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
One of my once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
One of my once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
One of my once once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
One of my once once once once
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
One of my once once once once once


In [ ]:
It Is Very